### ISSUE TITLE
Node Version Upgrade

### ISSUE THREAD

**Issue by jburgess** [AceFire6/file_changes#223]
Great action. Thanks! Possible to bump the node version to avoid the below warning?

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: AceFire6/file_changes@v0.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by AceFire6** [comment]
Hey @jburgess I'll do that now and get a new version out 👍

**Comment by AceFire6** [comment]
@jburgess I've released version 0.4.0 which includes the Node 20 upgrade

**Comment by jburgess** [comment]
@AceFire6 works as expected. Thanks for the fix!

**Comment by AceFire6** [comment]
Thanks for confirming 😁
